spring:
  application:
    name: ek-provider
server:
  port: 8081
eureka:
  instance:
    metadata-map:
      company-name: zys
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.netflix: DEBUG
