server:
  port: 9000
spring:
  application:
    name: spring-feign-invoker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
