server:
  port: 9000
spring:
  application:
    name: ek-invoker
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 30

logging:
  level:
    com.netflix: DEBUG
